export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_POST = 'FETCH_POST';
export API_CREATE_USER_REQUEST = 'API_CREATE_USER_REQUEST'
export API_CREATE_USER_REQUEST_SUCCESS ='API_CREATE_USER_REQUEST_SUCCESS'
export API_LOGIN_REQUEST = 'API_LOGIN_REQUEST'
export  API_LOGIN_REQUEST_SUCCESS = 'API_LOGIN_REQUEST_SUCCESS'
